### ISSUE TITLE
Request: pass the Note-Off velocity

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/BW_Midi_Sequencer#2]
Although rare, there can be some synths which use note-off velocity information;
for example, to apply a modifier to an envelope release curve.

**Comment by Wohlstand** [comment]
Made! Feel free to test this :fox_face: 
I made the logic to require one OF two: noteOff or noteOffVel. The assert will fail in only a case when both are not used.

**Comment by Wohlstand** [comment]
Closing this as velocity-equipped noteOff variant exist a whole year.
